# Site settings
# ******************************************************************************************************************************
baseurl = "http://localhost"
languageCode = "en-us"
title = "Elad Rom | Front End Developer"
publishdir = "../public"
googleAnalytics = ""
email = "iwfmp@yandex.com"

[params]
  name = "Elad Rom"
  description = "Front End Developer and CSS Wizard"

  # Navigation
  # ******************************************************************************************************************************
  [params.menu]

  [[params.menu.item]]
    name = "Expertise"
    icon = "icon-home"
    url  = "#expertise"

  [[params.menu.item]]
    name = "Portfolio"
    icon = "icon-briefcase"
    url  = "#portfolio"

  [[params.menu.item]]
    name = "Contact"
    icon = "icon-mail"
    url  = "#contact"

  # Header section
  # ******************************************************************************************************************************
  [params.header]
    title = "Hi, I'm Elad."
    subtitle = "I'm a CSS Wizard."
    buttonText = "Yes, I'm Available for hire"

  # Footer section
  # ******************************************************************************************************************************
  [params.footer]
    enable = true
    copyright = "Published under the Unlicense License"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"