# ******************************************************************************************************************************
# Site settings
# ******************************************************************************************************************************
baseURL = "http://eladrom.com"
languageCode = "en-us"
title = "Elad Rom | Front End Developer"
publishdir = "../public"
googleAnalytics = "UA-92279372-1"

[params]
  email = "iwfmp@yandex.com"