# Site settings
# ******************************************************************************************************************************
baseurl = "http://localhost"
languageCode = "en-us"
title = "Elad Rom | Front End Developer"
publishdir = "../public"
googleAnalytics = ""
email = "iwfmp@yandex.com"

[params]
  name = "Elad Rom"
  description = "Front End Developer and CSS Wizard"

  # Navigation
  # ******************************************************************************************************************************
  [params.menu]

  [[params.menu.item]]
    name = "Expertise"
    icon = "icon-home"
    url  = "#expertise"

  [[params.menu.item]]
    name = "Portfolio"
    icon = "icon-briefcase"
    url  = "#portfolio"

  [[params.menu.item]]
    name = "Contact"
    icon = "icon-mail"
    url  = "#contact"

  # Header section
  # ******************************************************************************************************************************
  [params.header]
    title = "Hi, I'm Elad."
    subtitle = "I'm a CSS Wizard."
    buttonText = "Yes, I'm Available for hire"

  # Contact section
  # ******************************************************************************************************************************
  [params.contact]
    title = "Want to work together?"
    description = "I'm currently accepting new projects and would love to hear about yours."
    description2 = "Please take a few minutes to tell me about it."
    buttonText = "Contact me!"

    # Form fields
    formName = "Name"
    formEmail = "Email"
    formPhone = "Phone"
    formMessage = "Tell me about your project"
    formButton = "Submit"

  # Thanks section
  # ******************************************************************************************************************************
  [params.thanks]
    title = "Your message was sent!"
    description = "Thank you for your submission! I'll get it touch with you to schedule a time to chat."
    description2 = "You should expect to hear from me in a day or so."

  # Footer section
  # ******************************************************************************************************************************
  [params.footer]
    enable = true
    copyright = "Published under the Unlicense License"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"